name: Redis Cluster

on: [push]

jobs:

  cluster:
    name: Cluster ${{ matrix.redis }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        redis: ['4.0.14', '6.2.0', '7.0.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # TODO: Start a Redis Cluster
      #   - Use ${{ matrix.redis }} for version
      #   - Must have at least 3 primary nodes with 1 replica each
      #   - Cluster must require a password for connections
      #   - Is `bitnami/redis-cluster` a good choice?
      - name: Start Redis cluster
        uses: vishnudxb/redis-cluster@1.0.5
        with:
          master1-port: 5000
          master2-port: 5001
          master3-port: 5002
          slave1-port: 5003
          slave2-port: 5004
          slave3-port: 5005


      - name: Install dependencies
        run: sudo apt-get install -y redis-tools

      - name: Health Check
        # TODO: Adjust ips/ports if needed
        run: redis-cli -p 5001 cluster nodes

      - name: Test PHP connection
        env:
          # TODO: Adjust ips/ports if needed
          REDIS_PRIMARIES: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381
          REDIS_AUTH: secret
        run: |
          docker ps -a
          php cluster.php
  
